name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      cli:
        description: run by command line
        default: uarn cypress run

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Get code 
      uses: actions/checkout@v2.7.0
      
    - name: Install dependences
      run: yarn install
      
    - name: Run E2E tests
      run: ${{ github.event.inputs.cli }}
